### ISSUE TITLE
Potential typo on homepage

### ISSUE THREAD

**Issue by machawk1** [emmadickson/emmadickson.github.com#63]
@emmadickson, on your homepage at https://emmadickson.info/, I noticed the sentence containing, "hire me for a freelance job, exhibt my artwork or talk".

Is `exhibt` perhaps a typo? I would submit a PR to "fix" it but (1) don't want to intrude on your personal site, (2) am unsure whether the HTML files in this repo are representative/statically generated, and (3) am uncertain whether this spelling is intentional.

Either way, I hope a GH issue is a suitable way to communicate this.

**Comment by emmadickson** [comment]
@machawk1 thank you!! This is so kind of you. The spelling is not intentional it's a hundred percent a typo. The html files in this repo are statically generated I tend to update the site kind of irregularly/only when I do a new thing I want to mention on the site. 

Opening an issue was perfect because it also reminded me that I want to improve some of the sites visuals/try out some other stuff. So thanks!
